#!/usr/bin/perl
# Diagnostic dump of doors world @garyd

$DoorsProg = "./doors_ng.py";

for ($y = -4; $y <= 4; $y++) {
  for ($x = -4; $x <= 4; $x++) {
    $s = `$DoorsProg $x $y`;
    $s =~ s/\n|\r/\t/gmo;
    print ("$s\n");
  }
  print ("\n");
}
